version: '3.4'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
  microservice1.api:
    image: erhangndz/microservice1:${version}
    container_name: microservice1-container
    build:
      context: .
      dockerfile: Microservice1.API/Dockerfile
  microservice2.api:
    image: erhangndz/microservice2:${version}
    container_name: microservice2-container
    build:
      context: .
      dockerfile: Microservice2.API/Dockerfile
volumes:
  sqlserver_volume: